# Generated by Django 5.1.2 on 2024-10-21 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campeonatos', '0005_alter_campeonato_data_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_horario', models.DateTimeField()),
                ('resultado', models.CharField(blank=True, max_length=50, null=True)),
                ('time_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_como_casa', to='campeonatos.participante')),
                ('time_fora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_como_fora', to='campeonatos.participante')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols_time_casa', models.PositiveIntegerField(default=0)),
                ('gols_time_fora', models.PositiveIntegerField(default=0)),
                ('jogo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_jogo', to='gerenciamento_campeonatos.jogo')),
            ],
        ),
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('data', models.DateTimeField()),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rodadas', to='campeonatos.campeonato')),
            ],
        ),
        migrations.AddField(
            model_name='jogo',
            name='rodada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to='gerenciamento_campeonatos.rodada'),
        ),
    ]
