# Generated by Django 5.1.2 on 2024-10-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_campeonatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='gols_time_casa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='gols_time_fora',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
