# Generated by Django 5.1.2 on 2024-11-06 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0003_rename_premiacao_campeonato_premiação'),
        ('gerenciamento_campeonatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RodadasClassificatorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(max_length=50)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rodadas_classificatorias', to='campeonatos.campeonato')),
            ],
        ),
    ]
