# Generated by Django 5.1.2 on 2024-11-06 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0003_rename_premiacao_campeonato_premiação'),
        ('gerenciamento_campeonatos', '0002_rodadasclassificatorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='RodadaEliminatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(max_length=50)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eliminatorias', to='campeonatos.campeonato')),
            ],
        ),
        migrations.CreateModel(
            name='JogoEliminatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_horario', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.CharField(blank=True, max_length=50, null=True)),
                ('time_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eliminatorias_como_casa', to='campeonatos.participante')),
                ('time_fora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eliminatorias_como_fora', to='campeonatos.participante')),
                ('rodada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to='gerenciamento_campeonatos.rodadaeliminatoria')),
            ],
        ),
    ]
