# Generated by Django 5.1.2 on 2024-11-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_campeonatos', '0003_rodadaeliminatoria_jogoeliminatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodadaeliminatoria',
            name='fase',
            field=models.CharField(choices=[('oitavas', 'Oitavas de Final'), ('quartas', 'Quartas de Final'), ('semi', 'Semifinais'), ('final', 'Final')], max_length=50),
        ),
    ]
