# Generated by Django 5.1.2 on 2024-11-06 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0003_rename_premiacao_campeonato_premiação'),
        ('gerenciamento_campeonatos', '0004_alter_rodadaeliminatoria_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogoeliminatorio',
            name='placeholder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jogoeliminatorio',
            name='time_casa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminatorias_como_casa', to='campeonatos.participante'),
        ),
        migrations.AlterField(
            model_name='jogoeliminatorio',
            name='time_fora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eliminatorias_como_fora', to='campeonatos.participante'),
        ),
    ]
