# Generated by Django 5.1.2 on 2024-11-06 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_campeonatos', '0005_jogoeliminatorio_placeholder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoEliminatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols_time_casa', models.PositiveIntegerField(blank=True, null=True)),
                ('gols_time_fora', models.PositiveIntegerField(blank=True, null=True)),
                ('jogo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_eliminatorio', to='gerenciamento_campeonatos.jogoeliminatorio')),
            ],
        ),
    ]
