# Generated by Django 5.1.3 on 2024-11-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_campeonatos', '0010_alter_penalidade_tipo_penalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalidade',
            name='tipo_penalidade',
            field=models.CharField(blank=True, choices=[('amarelo', 'Cartão Amarelo'), ('vermelho', 'Cartão Vermelho'), ('expulsao', 'Expulsão'), ('outro', 'Outro'), ('participante', 'Por Participante'), ('equipe', 'Por Equipe')], max_length=50, null=True),
        ),
    ]
