# Generated by Django 5.1.3 on 2024-11-13 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0005_delete_pontosparticipante'),
        ('gerenciamento_campeonatos', '0011_alter_penalidade_tipo_penalidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenalidadeEliminatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_penalidade', models.CharField(blank=True, choices=[('amarelo', 'Cartão Amarelo'), ('vermelho', 'Cartão Vermelho'), ('expulsao', 'Expulsão'), ('outro', 'Outro'), ('participante', 'Por Participante'), ('equipe', 'Por Equipe')], max_length=50, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalidades_eliminatorias', to='gerenciamento_campeonatos.jogoeliminatorio')),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalidades_eliminatorias', to='campeonatos.participante')),
            ],
        ),
    ]
