# Generated by Django 5.1.3 on 2024-11-13 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_campeonatos', '0012_penalidadeeliminatoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penalidadeeliminatoria',
            name='data',
        ),
    ]
