# Generated by Django 5.1.2 on 2024-10-15 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0002_inscricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='campeonato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricao_set', to='campeonatos.campeonato'),
        ),
    ]
