# Generated by Django 5.1.2 on 2024-11-05 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0002_rename_premiação_campeonato_premiacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campeonato',
            old_name='premiacao',
            new_name='premiação',
        ),
    ]
