# Generated by Django 5.1.2 on 2024-11-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0003_rename_premiacao_campeonato_premiação'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='eliminatorias_geradas',
            field=models.BooleanField(default=False),
        ),
    ]
