# Generated by Django 5.1.2 on 2024-10-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0003_alter_inscricao_campeonato'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='numero_maximo_participantes',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
