# Generated by Django 5.1.2 on 2024-10-21 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0005_alter_campeonato_data_fim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='email_participante',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='equipe_participante',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='nome_participante',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='participante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campeonatos.participante'),
            preserve_default=False,
        ),
    ]
