# Generated by Django 5.1.2 on 2024-10-21 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0006_remove_inscricao_email_participante_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participante',
            old_name='email',
            new_name='email_participante',
        ),
        migrations.RenameField(
            model_name='participante',
            old_name='equipe',
            new_name='equipe_participante',
        ),
        migrations.RenameField(
            model_name='participante',
            old_name='nome',
            new_name='nome_participante',
        ),
        migrations.AddField(
            model_name='participante',
            name='campeonato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='participante_set', to='campeonatos.campeonato'),
            preserve_default=False,
        ),
    ]
