# Generated by Django 5.1.2 on 2024-10-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0007_rename_email_participante_email_participante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='campeonato',
        ),
        migrations.AlterField(
            model_name='participante',
            name='email_participante',
            field=models.EmailField(max_length=100),
        ),
    ]
