# Generated by Django 5.1.2 on 2024-10-21 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0009_alter_participante_equipe_participante'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='campeonato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='participante_set', to='campeonatos.campeonato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participante',
            name='email_participante',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='participante',
            name='equipe_participante',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
