# Generated by Django 5.1.2 on 2024-10-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0010_participante_campeonato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='equipe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
