# Generated by Django 5.1.2 on 2024-10-23 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0011_inscricao_equipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='equipe',
        ),
    ]
